[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
click_game = "2PCEtm6r8dtSxJrqMLhGQDdAA1rq915NsD7WRpLUzdyy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
